#ifndef MESHLET_CONSTANTS
#define MESHLET_CONSTANTS

const int MAX_VERTEX_COUNT = 64;
const int MAX_PRIMITIVE_COUNT = 126;
const int MAX_PRIMITIVE_INDICES_COUNT = 378;
const int MAX_TASK_COUNT = 32;
const int GROUP_SIZE = 32;

#endif MESHLET_CONSTANTS